#!/usr/bin/env bash
# configures nginx on brand new Ubuntu machine 
sudo apt-get -y update
sudo apt-get -y install nginx

sudo rm -f /var/www/html/*

echo "Hello World!" > index.html
echo "Ceci n'est pas une page" > 404.html

sudo mv index.html /var/www/html/
sudo mv 404.html /var/www/html/

printf 'server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	add_header X-Served-By $hostname;

	error_page 404 /404.html;

	rewrite ^/redirect_me http://youtube.com/ permanent;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}
}' > /etc/nginx/sites-available/default

sudo service nginx restart
