#!/usr/bin/env bash
# configures HAproxy load balancer
#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy 1> /dev/null

printf "
frontend my_frontend
        bind :80
        default_backend my_backend

backend my_backend
        balance roundrobin
        server 360907-web-01 54.237.72.179:80 check
        server 360907-web-02 52.23.245.31:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg 1> /dev/null

sudo service haproxy restart

