#!/usr/bin/env bash
#  displays the content of the file /etc/passwd,
# only display username, user id and Home directory path for the user.

list=$(cat /etc/passwd)

for l in $list
do
	echo "$l" | cut -d ":" -f1,3,6
done
