#!/usr/bin/env bash
#  displays the content of the file /etc/passwd,
# only display username, user id and Home directory path for the user.

file="/etc/passwd"

while read -r line;
do
	echo "$line" | cut -d ":" -f1,3,6
done < "$file"
