#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes,
# display hours from 0 to 12,
# display minutes from 1 to 59

h=0

while [[ h -le 12 ]]
do
	echo "Hour: $h"

	s=1

	while [[ s -le 59 ]]
	do
		echo $s

		((s++))
	done

	((h++))
done
